# Generated by Django 5.2.7 on 2025-11-04 13:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnp', models.CharField(help_text='Personal identification number (13 digits).', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'CNP must have exactly 13 digits')])),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager for this user (nullable for managers).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF')], max_length=4)),
                ('period', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=512)),
                ('file_path', models.CharField(help_text='Absolute or storage path', max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='CREATED', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_employee_files', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_manager_files', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = open-ended', null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='RON', max_length=3)),
                ('vacation_days_per_year', models.PositiveIntegerField(default=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Anchor date = first day of the month')),
                ('working_days', models.PositiveIntegerField(default=0)),
                ('vacation_days_taken', models.PositiveIntegerField(default=0)),
                ('bonus_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_salary', models.DecimalField(decimal_places=2, help_text='Net or gross as per your business rules', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period', 'user'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['manager'], name='slipApp_use_manager_34b813_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['MANAGER', 'EMPLOYEE'])), name='user_role_valid'),
        ),
        migrations.AddIndex(
            model_name='auditfile',
            index=models.Index(fields=['created_at'], name='slipApp_aud_created_58d6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfile',
            index=models.Index(fields=['manager', 'period'], name='slipApp_aud_manager_0662a7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfile',
            index=models.Index(fields=['employee', 'period'], name='slipApp_aud_employe_9288f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditfile',
            constraint=models.CheckConstraint(condition=models.Q(('file_type__in', ['CSV', 'PDF'])), name='audit_filetype_valid'),
        ),
        migrations.AddConstraint(
            model_name='auditfile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CREATED', 'SENT', 'FAILED'])), name='audit_status_valid'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['user', 'start_date'], name='slipApp_con_user_id_fe36cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='contract_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['period'], name='slipApp_pay_period_a8122b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('user', 'period'), name='uniq_user_period'),
        ),
    ]
